name: raviqqe/markdown-link-check
description: Checks links in Markdown files
branding:
  icon: link
  color: green
inputs:
  paths:
    description: Paths to Markdown files
    required: false
    default: "**/*.md"
outputs: {}
runs:
  using: composite
  steps:
    - uses: lycheeverse/lychee-action@v1
      with:
        args: --verbose --no-progress --exclude ^https://help.openai.com ${{ inputs.paths }}
        fail: true
