name: raviqqe/markdown-link-check
description: Checks links in Markdown files
branding:
  icon: link
  color: green
inputs:
  paths:
    description: Paths to Markdown files
    required: false
    default: "**/*.md"
outputs: {}
runs:
  using: composite
  steps:
    - uses: lycheeverse/lychee-action@v2
      with:
        args: >
          --accept 200..300,403
          --exclude ^https://help.openai.com/
          --exclude ^https://stackoverflow.com/
          --exclude ^https://www.gnu.org/software/guile/
          --no-progress
          --verbose
          ${{ inputs.paths }}
        fail: true
