name: release
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  spell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v5
        with:
          files: "**/*.md"
